workflows:
  ios-web-workflow:
    name: Build iOS (unsigned) and Web
    max_build_duration: 45
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build iOS (unsigned)
        script: flutter build ios --release --no-codesign
      - name: Build Web
        script: flutter build web
    artifacts:
      - build/ios/iphoneos/*.app
      - build/web/**/*

