workflows:
  ios-web-build:
    name: iOS and Web Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Clean project
        script: |
          flutter clean
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          # ── Sanitiza las .xcconfig para quitar TODO flag -G* ──
          find Pods -type f -name '*.xcconfig' -exec sed -i '' 's/-G[^ ]*//g' {} +
          # ── Limpia flags -G también en los proyectos de Pods (.pbxproj) ──
          find Pods -type f -name '*.pbxproj' -exec sed -i '' 's/ -G[^ ]*//g' {} +
          cd ..
      - name: Build iOS for simulator
        script: |
          flutter build ios --simulator --debug
      - name: Build Web
        script: |
          flutter build web
    artifacts:
      - build/ios/iphonesimulator/*.app
      - build/web/**
    publishing:
      email:
        recipients:
          - javigarciash9@gmail.com