workflows:
  ios-web-build:
    name: iOS and Web Build (No Code Signing)
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Clean project
        script: |
          flutter clean
      - name: Get dependencies
        script: |
          flutter pub get
          cd ios
          pod install || true
          cd ..
      - name: Build iOS for simulator
        script: |
          flutter build ios --simulator --no-codesign
      - name: Build Web
        script: |
          flutter build web
    artifacts:
      - build/ios/iphonesimulator/*.app
      - build/web/**
    publishing:
      email:
        recipients:
          - javigarciash9@gmail.com