workflows:
  ios-web-build:
    name: iOS and Web Build
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Clean project
        script: |
          flutter clean
      - name: Get dependencies
        script: |
          flutter pub get
      - name: Install CocoaPods dependencies
        script: |
          cd ios
          pod install
          cd ..
      - name: Build iOS for device (ipa)
        script: |
          flutter build ios --release --no-codesign
      - name: Build Web
        script: |
          flutter build web
    artifacts:
      - build/ios/iphoneos/*.ipa
      - build/web/**
    publishing:
      email:
        recipients:
          - javigarciash9@gmail.com
