name: benchly
description: A Flutter app for sharing and discovering top banks
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

  # Icon fonts
  cupertino_icons: ^1.0.2

  # Maps & geolocation
  google_maps_flutter: ^2.12.1
  geolocator: ^14.0.0

  # Firebase
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  google_sign_in: ^6.1.5

  # UI & utilities
  flutter_rating_bar: ^4.0.1
  page_transition: ^2.1.1
  animations: ^2.0.7
  csv: ^6.0.0

  # Ads
  google_mobile_ads: ^6.0.0

  # Internationalization
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0

flutter:
  generate: true
  uses-material-design: true

  # Si en el futuro añades recursos (imágenes, JSON…), 
  # crea la carpeta `assets/` y vuelve a descomentar:
  # assets:
  #   - assets/

