platform :ios, '12.0'
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

flutter_application_path = File.expand_path('..')
load File.join(flutter_application_path, '.flutter-plugins-dependencies')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  # Firebase Core y Firestore
  pod 'FirebaseCore'
  pod 'FirebaseFirestore'

  # gRPC pinneado a una versión estable anterior
  pod 'gRPC-Core', '1.50.0'
  pod 'gRPC-C++',  '1.50.0'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    # Forzar deployment target a iOS 12.0
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET']    = '12.0'
      config.build_settings['CLANG_CXX_LANGUAGE_STANDARD']   = 'c++14'
      config.build_settings['CLANG_CXX_LIBRARY']             = 'libc++'

      # Eliminar cualquier bandera que empiece por '-G'
      config.build_settings.keys.each do |key|
        next unless config.build_settings[key].is_a?(String)
        flags = config.build_settings[key].split.reject { |f| f.start_with?('-G') }
        config.build_settings[key] = flags.join(' ')
      end
    end
  end
end