platform :ios, '12.0'

ENV['COCOAPODS_DISABLE_STATS'] = 'true'

flutter_application_path = File.expand_path('..')
load File.join(flutter_application_path, '.flutter-plugins-dependencies')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  pod 'Firebase/Core'
  pod 'Firebase/Firestore'
end